# Python basics homework

In [1]:
import numpy as np

#### 1° Task

1. Create a list with the names of every planet in the solar system (in order)
2. Have Python tell you how many planets there are by examining your list
3. Print the first four planets in the solar system (the rocky planets)
4. Print the planet if it has an s at the end in its name

In [2]:
planets=["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]

In [3]:
print("There are", len(planets), "planets")

There are 8 planets


In [4]:
print ("The rocky planets in the solar system are:") 
planets[0:4]

The rocky planets in the solar system are:


['Mercury', 'Venus', 'Earth', 'Mars']

In [5]:
print('The planets that have an "s" in their name are:',planets[1],",",planets[3],",",planets[5],", and",planets[6])

The planets that have an "s" in their name are: Venus , Mars , Saturn , and Uranus


#### 2° Task

A colleague from the United States shared with us the following temperature measurement, given in Fahrenheit:

$$
T = 30.3^\circ \text{F}
$$

Convert this value to degrees Celsius, knowing that:
$$[^\circ \text{C}] = \frac{5}{9} ([^\circ \text{F}] - 32) $$ 

Requirements:

* Assign the received data to a variable.
* Apply the unit transformation using this variable.
* Save the data in Celsius in another variable.
* Use the print function to display both results.

In [6]:
Tf=30.3
Tc=(5/9)*(Tf-32)
print("The temperature in Fahrenheit is",Tf,"and the temperature in Celsius is", Tc)

The temperature in Fahrenheit is 30.3 and the temperature in Celsius is -0.9444444444444441


#### 3° Task

Given the array: `([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])`, investigate the `numpy` library documentation for reshape the array to be 4x4.

In [7]:
array_old=([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("array_old")
print(array_old)
array_new=np.reshape(array_old,(4,4))
print("array_new")
print(array_new)

array_old
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
array_new
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### 4° Task

`NumPy` allows us to apply mathematical functions.

Calculate the sine and cosine of the angles 0, 30, 45, 60 and 90 given in degrees:
1. Create an array with the angles in degrees.
2. Convert the angles to radians.
3. Calculate the sine and cosine of these angles and store them in two different arrays.

_Investigate the `numpy` library to find the functions to convert the angles from degrees to radians and calculate the sine and cosine._

In [8]:
angles_deg=[0,30,45,60,90]
angles_rad=np.deg2rad(angles_deg)
print("angles in degrees:",angles_deg)
print("angles in radians:",angles_rad)
sin_angles=np.sin(angles_rad)
print("sin:", sin_angles)
cos_angles=np.cos(angles_rad)
print("cos:", cos_angles)

angles in degrees: [0, 30, 45, 60, 90]
angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


#### 5° Task


**Finite differences | Diferencias finitas**

A common approximation for computing derivatives of functions is a finite difference approximation:

$$\frac{d}{dx} y(x) = \frac{y(x + \Delta x) - y(x)}{\Delta x}$$

or for discrete data

$$\frac{d}{dx} y(x_i) = \frac{y(x_i + \Delta x) - y(x_i)}{\Delta x} = \frac{y(x_{i+1}) - y(x_i)}{x_{i+1} - x_{i}}$$

This operation can be accomplished using index, slice and vectorized algebraic operations.
Try to solve it for the quadratic function!

Now, read the numpy documentation to find a function to calculate $\frac{d}{dx} y(x_i)$.

In the case of the quadratic function, $$y=ax^2+bx+c$$

the first derivative is

$$\frac{d}{dx} y(x_i) = \frac{ax_{i+1}^2+bx_{i+1}+c-ax_{i}^2-bx_{i}-c}{x_{i+1}-x_i}=\frac{a*(x_{i+1}^2-x_{i}^2)+bx_{i+1}-bx_{i}}{x_{i+1}-x_i}$$

En numpy encontré la función poly1d.deriv() para obtener derivadas de polinomios. La función polyder() hace lo mismo. También encontré que, con la librería sympy se puede hacer matemática simbólica y es posible calcular derivadas con la función diff() o derivative.

In [9]:
#ejemplo con librería numpy
coef=[5,-3,4,9] #coeficientes del polinomio
p=np.poly1d(coef) #construcción del polinomio
dp_dx=np.poly1d.deriv(p) #cálculo de la derivada
print("La derivada de")
print(p)
print("es")
print(dp_dx)

La derivada de
   3     2
5 x - 3 x + 4 x + 9
es
    2
15 x - 6 x + 4
